### ISSUE TITLE
Actualizar e/r con las modificaciones que se realizen en la bd

### ISSUE THREAD

**Issue by saul205** [UNIZAR-30226-2020-10/back-end#15]

**Comment by AlbertoCalvoRubio** [comment]
Añadido:
- Usuario: foto
- Álbum: foto

**Comment by AlbertoCalvoRubio** [comment]
Añadido a petición de @Alvarogd6 :
- SeriePodcast
- CapituloPodcast
- Relaciones: `escuchado` `compuesta`

**Comment by AlbertoCalvoRubio** [comment]
Añadido:
- ListaPodcast
- Relaciones: `aparece` entre SeriePodcast y ListaPodcast y `tiene` entre Usuario y ListaPodcast
