### ISSUE TITLE
Buscar información sobre eliminación en cascada en sqlAlchemy

### ISSUE THREAD

**Issue by saul205** [UNIZAR-30226-2020-10/back-end#16]
Al eliminar algunas entidades como usuarios se busca que la información que estos almacenaban se borre también.

**Comment by AlbertoCalvoRubio** [comment]
Indicar en la clase con la relationship: cascade='delete'

**Comment by AlbertoCalvoRubio** [comment]
Uso de ondelete="CASCADE" en las claves extranjeras para utilizar el cascade de forma nativa
