### ISSUE TITLE
Diagrama E/R

### ISSUE THREAD

**Issue by saul205** [UNIZAR-30226-2020-10/back-end#2]
Preparar primera versión del esquema entidad relación de nuestra bd

**Comment by AlbertoCalvoRubio** [comment]
Corregido atributos que no eran únicos

**Comment by AlbertoCalvoRubio** [comment]
Añadido notificación como entidad y herencia de los distintos tipos. Pendiente de aprobación en reunión para cerrar issue

**Comment by AlbertoCalvoRubio** [comment]
Visto bueno en la reunión del 3/03/2020

**Comment by AlbertoCalvoRubio** [comment]
Cerramos la versión inicial y continuamos las modificaciones que vayan surgiendo en el nuevo issue
