### ISSUE TITLE
Fichero flask-SQLAlchemy para base de datos

### ISSUE THREAD

**Issue by saul205** [UNIZAR-30226-2020-10/back-end#6]
Investigación para crear, manejar la BD usando sqlalchemy

**Comment by AlbertoCalvoRubio** [comment]
Añadidas relaciones
Bibliografía:
[Creating One-To-Many](https://www.youtube.com/watch?v=juPQ04_twtA&list=WL&index=2&t=388s)
[Creating Many-To-Many](https://www.youtube.com/watch?v=OvhoYbjtiKc&list=WL&index=3&t=0s)

**Comment by AlbertoCalvoRubio** [comment]
Posible solución a almacenamiento de canciones en binarios
[Python, how to read bytes from file and save it?](https://stackoverflow.com/questions/6787233/python-how-to-read-bytes-from-file-and-save-it)

**Comment by AlbertoCalvoRubio** [comment]
Almacenamiento de las canciones mediante path
Clases subidas en db.py
Clases y relaciones testeadas en db_test
Crear la base de datos: db.create_all()
Poblar: from db_test import poblar
Borrar todas las tablas: db.drop_all()

**Comment by AlbertoCalvoRubio** [comment]
Añadido token y fcm_token
